# Generated by Django 6.0.1 on 2026-02-03 07:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grades',
            name='date_grade',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='grades',
            name='grade',
            field=models.IntegerField(default=0),
        ),
    ]
